---
- hosts: dnsprime
  become_user: root
  vars:
    zonename: nbb.ops
    master: 192.168.132.2
  tasks:
    - name: Make sure bind is installed
      package
        name: bind
        state: latest
    - name: copy config file to client
      template: src=named.j2 dest=/etc/named.conf
        owner=root group=named mode=0644
    - name: make sure named is running
      service:
        name: named
        state: restarted
  handlers:
    - name: restart named
      service:
        name: named
        state: restarted
